name: Build Release Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          debhelper \
          devscripts \
          cowsay
          
    - name: Get version from tag
      id: version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "version=dev" >> $GITHUB_OUTPUT
          echo "tag=dev" >> $GITHUB_OUTPUT
        fi
        
    - name: Update version in changelog
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        # Update the version in debian/changelog
        VERSION="${{ steps.version.outputs.version }}"
        sed -i "1s/1\.0\.0-1/${VERSION}-1/" debian/changelog
        
    - name: Build Debian package
      run: |
        echo "Building release .deb package..."
        debuild -b -us -uc
        ls -la ../*.deb
        
    - name: Rename package with version
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        if [ "$VERSION" != "dev" ]; then
          mv ../cowgreeting_*.deb ../cowgreeting_${VERSION}_all.deb
        fi
        ls -la ../*.deb
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ../cowgreeting_*.deb
        body: |
          ## CowGreeting Release ${{ steps.version.outputs.tag }}
          
          ### Installation
          ```bash
          # Download the .deb file and install
          sudo dpkg -i cowgreeting_${{ steps.version.outputs.version }}_all.deb
          
          # Or if dependencies are missing:
          sudo apt-get install -f
          ```
          
          ### Usage
          ```bash
          # Run the greeting
          cowgreeting
          # or
          greetcow
          ```
          
          ### Features
          - ✅ Time-aware greetings (morning/afternoon/evening)
          - ✅ Automatic plugin directory creation (`~/.config/cowgreeting/plugins/`)
          - ✅ Configurable date/time formats
          - ✅ Plugin system for extensibility
          - ✅ Automatic cowsay dependency installation
          
          See the [README](README.md) for full documentation.
        draft: false
        prerelease: false
        
    - name: Upload artifact (non-release)
      if: '!startsWith(github.ref, ''refs/tags/'')'
      uses: actions/upload-artifact@v4
      with:
        name: cowgreeting-deb-development
        path: ../cowgreeting_*.deb
        retention-days: 7 